config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categoryskills do
    resources :skills
  end
  resources :categorystories do
    resources :stories
  end
  resources :contactmes, only: [:index,:new, :create]
  resources :homes
  root "homes#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates_presence_of :title,:author,:description,:image
  has_attached_file :image, styles: {
    medium: "300x300>",
    thumb: "100x100>"
  }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/categoryskill.rb
class Categoryskill < ApplicationRecord
  validates_presence_of :categoryname
  has_many :skills
end

app/models/categorystory.rb
class Categorystory < ApplicationRecord
  validates_presence_of :categoryname
  has_many :storys
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_presence_of :companyname,:address,:email,:phone,:website
end

app/models/contactme.rb
class Contactme < ApplicationRecord
  validates :name,:email,:subject,:message,presence: true
end

app/models/education.rb
class Education < ApplicationRecord
  validates_presence_of :title,:start_education,:end_education,:description
end

app/models/experience.rb
class Experience < ApplicationRecord
  validates_presence_of :title,:position,:startjobdate,:description
end

app/models/personal.rb
class Personal < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :position
  validates_presence_of :description
  validates_presence_of :dateofbirth
  validates_presence_of :address
  validates_presence_of :email
  validates_presence_of :phone
  validates_presence_of :socialmedianame

  has_attached_file :image, styles: {
    medium: "300x300>",
    thumb: "100x100>"
  }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :categoryskill
  validates_presence_of :skillname,:progressbar
  has_attached_file :image, styles: {
    medium: "300x300>",
    thumb: "100x100>"
  }
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :categorystory
  validates_presence_of :title,:description,:post_date,:image
  has_attached_file :image, styles: {
    medium: "300x300>",
    thumb: "100x100>"
  }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contactmes_helper.rb
module ContactmesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/personal_helper.rb
module PersonalHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/stroies_helper.rb
module StroiesHelper
end

app/views/add/_blog.html.erb
<div class="main-title">
  <h1>latest news</h1>
    <div class="divider">
      <div class="zigzag large clearfix "  data-svg-drawing="yes" >
        <svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
        <path d="M1.357,12.26 10.807,2.81 20.328,12.332
          29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
        </svg>
      </div>
    </div>
</div>
<!--End main title-->
<!--Content-->
              <div class="content">

                <!--Block content-->
                <div class="block-content ">
                <!--Works-->
                <div class="blog">
<!--Row-->
  <%@blog.each do |blog|%>
                <div class="row">


                  <!--Blog posts-->
                  <div class="block-posts ">
                    <!--Block post-->
                    <div class="block-post ">
                      <div class="col-md-12">
                        <div class="post-media margBSmall">
                          <img src="<%=blog.image%>" alt=""/>
                        </div>
                        <div class="post-title">
                          <a href="blog_single.html">
                            <h1><%=blog.title%></h1>
                          </a>
                        <span class="meta-date"><%=blog.created_at%></span>
                                      </div>


                      <ul class="post-meta">
                        <li>
                          <i class="icon-user"></i>
                            <span>Post by
                              <a href="#"><%=blog.author%></a>
                            </span>
                          </li>
                      </ul>

                      <hr>

                      <p><%=blog.description%></p>


                        <a href="blog_single.html" class="but brd">Read More</a>

                      </div>


                      <div class="clearfix"></div>


                      <!--Divider-->
                      <div class="divider-m tCenter margTSmall margBottom clearfix">
                        <div class="col-md-12">
                          <div class="zigzag medium clearfix "  data-svg-drawing="yes" >
    <svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="45" height="5" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
    <path d="M1.357,12.26 10.807,2.81 20.328,12.332
      29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
    </svg>
  </div>
                        </div>
                      </div>
                      <!--End divider-->




                    </div>
                    <!--End block post-->

                  </div>
                  <!--End blog posts-->


                  </div>
                  <!--End row-->
                  <%end%>
                    <div class="block-all tCenter margTSmall margBSmall">
                    <a class="but  brd" href="blog.html">View all blog posts</a>
                    </div>




                              </div>
                <!--End blog-->

                </div>
                <!--End block content-->



                </div>
                <!--End content-->

app/views/add/_contact.html.erb
<div class="contact">
<!--Main title-->

                <div class="main-title">
                  <h1>send me an email</h1>
                    <div class="divider">
                        <div class="zigzag large clearfix "  data-svg-drawing="yes" >
  <svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
  <path d="M1.357,12.26 10.807,2.81 20.328,12.332
    29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
  </svg>
  </div>
  </div>
                </div>

              <!--End main title-->




          <!--Content-->
          <div class="content">

            <!--Block content-->
            <div class="block-content ">

            <!--Contact-->
            <div class="block-contact margBSSmall">

              <!--Row-->
              <div class="row">

                  <%=form_for @contactme, :html => {:class => "contact-form"} do |f|%>
                  <div class="input-columns clearfix">
                    <%if @contactme.errors.any?%>
                      <%@contactme.errors.full_messages.each do |message|%>
                      <div class="alert alert-warning" role="alert"><i class="fa fa-warning"></i> <%=message%></div>
                      <%end%>
                    <%end%>
                    <div class="column1">
											<div class="column-inner">
                        <%=f.text_field :name, placeholder:"Name" ,:id=>"name"%>
											</div>
										</div>

										<div class="column2">
											<div class="column-inner">
                        <%=f.text_field :email, placeholder:"Email",:id=>"email"%>
											</div>
										</div>
															<!--End column-->
                  </div>
                  <%=f.text_field :subject, placeholder:"Subject",:id=>"subject"%>

                  <%=f.text_area :message, placeholder:"Message",:id=>"message"%>

                  <div class="form login">
                    <div class="form_field" style="padding-left:15px;padding-right:15px;padding-top:10px;">
                      <%=f.submit "Submit"%>
                    </div>
                  </div>
                  <%end%>

              </div>
              <!--End row-->

                        </div>
          <!--End contact-->

          </div>
          <!--End block content-->



          </div>




                  <!--Main title-->

                    <div class="main-title">
                      <h1>contact info</h1>
                        <div class="divider">
                            <div class="zigzag large clearfix "  data-svg-drawing="yes" >
      <svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
      <path d="M1.357,12.26 10.807,2.81 20.328,12.332
        29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
      </svg>
      </div>
      </div>
                    </div>

                  <!--End main title-->




              <!--Content-->
              <div class="content">

                <!--Block content-->
                <div class="block-content ">

                <!--Info-->
                <div class="block-info">

                  <!--Row-->
                  <div class="row">
                  <%@contact.each do |contact|%>
                  <div class="col-md-12">

                    <div class="info-holder   margTMedium">

                    <!--Address info-->
                    <div class="address-info">
                    <i class="fa fa-map-marker"></i>
                    <p><%=contact.companyname%>.<%=contact.address%> <br><%=contact.city%>.</p>
                    </div>
                    <!--End address info-->


                    <!--Contact info-->
                    <div class="contact-info tCenter">
                    <ul>
                      <li><div class="ico"><i class="fa fa-envelope"></i></div>
                      <p>Email : <%=contact.email%> </p></li>
                      <li><div class="ico"><i class="fa fa-phone"></i></div>
                      <p>Tel : <%=contact.phone%></p></li>
                      <li><div class="ico"><i class="fa fa-link"></i></div>
                        <p>WebSite : <a href="http://<%=contact.website%>"><%=contact.website%></a></p></li>
                    </ul>
                    </div>
                    <!--End contact info-->

                    </div>

                  </div>
                  <%end%>
                  </div>
                  <!--End row-->

                            </div>
              <!--End info-->

              </div>
              <!--End block content-->



              </div>
              <!--End content-->




              <div class="main-title">
                              <h1>map location</h1>
                                <div class="divider">
                                    <div class="zigzag large clearfix "  data-svg-drawing="yes" >
              <svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
              <path d="M1.357,12.26 10.807,2.81 20.328,12.332
                29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
              </svg>
              </div>
              </div>
                            </div>
                        <!--Content-->
                        <div class="content">

                          <!--Block content-->
                          <div class="block-content ">

                          <!--Map-->
                          <div class="block-map">

                            <!--Row-->
                            <div class="row">


                            <div class="col-md-12">
                              <%@contact.each do |contact|%>
                                <div id="map">
                                  <iframe src="https://www.google.com/maps/embed?pb=<%=contact.map%>" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
                                </div>
                              <%end%>
                            </div>

                            </div>
                            <!--End row-->

                                      </div>
                        <!--End map-->

                        </div>
                        <!--End block content-->



                        </div>
                        <!--End content-->




              <!--Main title-->

          <!--End content-->





              <!--Button-->




                </div>

app/views/add/_education.html.erb
<div class="main-title">
  <h1>education</h1>
    <div class="divider">
        <div class="zigzag large clearfix "  data-svg-drawing="yes" >
<svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
<path d="M1.357,12.26 10.807,2.81 20.328,12.332
29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
</svg>
</div>
</div>
</div>
<!--End main title-->
  <!--Content-->
  <div class="content">
    <!--Block content-->
    <div class="block-content">
    <!--Timeline-->
    <div class="timeline education">
                      <!--Row-->
      <div class="row ">
        <div class="col-md-12">
          <!--Experience holder-->
          <div class="exp-holder margTop">
          <!--Experience-->
          <%@education.each do |edu|%>
          <div class="exp">
          <div class="hgroup" >
            <h4><%=edu.title%></h4>
            <h6><i class="icon-calendar"></i><%=edu.start_education%> - <%=edu.end_education%></h6>
          </div>
            <p><%=edu.description%></p>
          </div>
          <%end%>
          <!--End experience-->
            <!--End experience-->
          </div>
          <!--End experience holder-->
        </div>


      </div>
      <!--End row-->

                  </div>
    <!--End timeline-->

    </div>
    <!--End block content-->


</div>
<!--End content-->

app/views/add/_experience.html.erb
<div class="main-title">
  <h1>experience</h1>
    <div class="divider">
        <div class="zigzag large clearfix "  data-svg-drawing="yes" >
<svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
<path d="M1.357,12.26 10.807,2.81 20.328,12.332
29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
</svg>
</div>
</div>
</div>
<!--End main title-->

<!--Content-->
<div class="content">
  <!--Block content-->
  <div class="block-content ">
  <!--Timeline-->
  <div class="timeline experience">
                    <!--Row-->
    <div class="row ">
      <div class="col-md-12">
        <!--Experience holder-->
        <div class="exp-holder margTop">
        <!--Experience-->
        <%@experience.each do |ex|%>
        <div class="exp">
        <div class="hgroup" >
          <h4><%=ex.position%> </h4>
          <h6><i class="fa fa-calendar"></i><%=ex.startjobdate%> - <span class="current">Current</span></h6>
        </div>
        <p><%=ex.description%></p>
        </div>
        <%end%>
        <!--End experience-->
      </div>
        <!--End experience holder-->
      </div>
    </div>
    <!--End row-->
  </div>
  <!--End timeline-->
  </div>
  <!--End block content-->
</div>
<!--End content-->

app/views/add/_footer.html.erb
<div class="button margTop ofsInTop tCenter">

    <div class="divider">
        <div class="zigzag large clearfix "  data-svg-drawing="yes" >
<svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
<path d="M1.357,12.26 10.807,2.81 20.328,12.332
29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
</svg>
</div>
</div>


                  <!--Row-->
  <div class="row ">


    <div class="col-md-12">
      <!-- <a class="but opc-1 ico" href="#">Download my cv</a> -->
      <%=link_to "Contact Me",new_contactme_path,:class=>"but opc-1 ico"%>
    </div>



    </div>
    <!--End row-->


                </div>

app/views/add/_js-partial.html.erb
<script>

(function($) {
  "use strict";

$(document).ready(function(){

	$('#wrapper').easytabs({
	animate			: true,
	updateHash		: false,
	transitionIn	:'fadeIn',
	transitionOut	:'fadeOut',
	animationSpeed	:100,
	tabActiveClass	:'active',
	tabs            :' #main-nav.tabbed > ul > li ',
	transitionInEasing: 'linear',
  	transitionOutEasing: 'linear'

});


//---------------------------------- Google map location -----------------------------------------//


$('#wrapper').bind('easytabs:after', function() {




		var styles = [
				        {
				            stylers: [
				                { saturation: -100 }

				            ]
				        },{
				            featureType: 'road',
				            elementType: 'geometry',
				            stylers: [
				                { hue: "#74b7b0" },
				                { visibility: 'simplified' }
				            ]
				        },{
				            featureType: 'road',
				            elementType: 'labels',
				            stylers: [
				                { visibility: 'on' }
				            ]
				        }
				      ],

				       lat = -33.867487,
				       lng = 151.20699,





				      customMap = new google.maps.StyledMapType(styles,
				          {name: 'Styled Map'}),


				      mapOptions = {
				          zoom: 14,
						scrollwheel: false,
						disableDefaultUI: true,
				          center: new google.maps.LatLng( lat, lng ),
				          mapTypeControlOptions: {
				              mapTypeIds: [google.maps.MapTypeId.ROADMAP]
				          }
				      },
				      map = new google.maps.Map(document.getElementById('map'), mapOptions),
				      myLatlng = new google.maps.LatLng( lat, lng ),




				      marker = new google.maps.Marker({
				        position: myLatlng,
				        map: map,
						icon: {
						            url: 'img/marker.png',
						            scaledSize: new google.maps.Size(26, 42)
						        }
				      });





				      map.mapTypes.set('map_style', customMap);
				      map.setMapTypeId('map_style');








});

//---------------------------------- End google map location -----------------------------------------//


});

})(jQuery);

</script>

app/views/add/_latestpost.html.erb
<div class="main-title">
  <h1>Latest Post</h1>
    <div class="divider">
        <div class="zigzag large clearfix "  data-svg-drawing="yes" >
<svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
<path d="M1.357,12.26 10.807,2.81 20.328,12.332
29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
</svg>
</div>
</div>
</div>

<!--End main title-->

<!--Content-->
<div class="content">
  <!--Block content-->
  <div class="block-content ">
  <!--Testimonilas-->
  <div class="testimonials">
                    <!--Row-->
    <div class="row ">
    <div class="col-md-12">
      <!--Slider-->
      <div class="testi clearfix ">
        <ul id="testimonial-carousel">
        <%@latestposts.each do |late|%>
        <li>
          <div class="block-quote">
          <div class="block-img"><img alt="" src="<%=late.image%>"></div>
          <div class="block-icon"><i class="icon-quote"></i></div>
          <h3 class="block-profile"><%=late.title%>   <span> <%=late.created_at%></span></h3>
          <blockquote><%=late.description%></blockquote>

          </div>
         </li>
         <%end%>
        </ul>

          </div>
      <!--End  slider-->


    </div>


      </div>
      <!--End row-->


                  </div>
    <!--End testimonials-->

    </div>
    <!--End block content-->


</div>
<!--End content-->

app/views/add/_left-content.html.erb
<div class="col-md-3 nopr left-content">
      <!--Main header-->
      <div class="main-header">
      <!--Profile image-->
      <%@personals.each do |personal|%>
      <figure class="img-profile">
        <img src="<%=personal.image%>" alt=""/>

        <figcaption class="name-profile">
          <span><%=personal.name%> <sup>&reg;</sup></span>
        </figcaption>

      </figure>
      <%end%>
      <!--End profile image-->

          <!--Main navigation-->
            <nav id="main-nav" class="main-nav clearfix tabbed">

            <ul>
              <li><%=link_to "Back To Home", 'javascript:history.go(-1);'%></li>

            </ul>


            </nav>
          <!--End main navigation-->

    </div>
    <!--End main header-->

    <div class="bottom-header bgWhite ofsTSmall ofsBSmall tCenter">
      <ul class="social">
      <li><a href="#"><i class="fa fa-facebook"></i></a></li>
      <li><a href="#"><i class="fa fa-twitter"></i></a></li>
      <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
    </ul>

    <p>&copy; 2017 Ai Solution</p>

    </div>


</div>
<!--End left content-->

app/views/add/_mywork.html.erb
<div class="main-title">
  <h1>My Stories</h1>
    <div class="divider">
      <div class="zigzag large clearfix "  data-svg-drawing="yes" >
        <svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
        <path d="M1.357,12.26 10.807,2.81 20.328,12.332
        29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
        </svg>
      </div>
    </div>
</div>
<!--End main title-->
<!--Content-->
<div class="content">
  <!--Block content-->
  <div class="block-content ">
    <!--Works-->
    <div class="works">
      <!--Row-->
      <div class="row">
        <div class="block-filter tCenter">
          <ul id="category" class="filter">
            <li><a data-filter="all" href="#" class="active">all</a></li>
            <%@categorystory.each do |cate|%>
              <li><a data-filter="<%=cate.cname%>" href="#"><%=cate.categoryname%></a></li>
            <%end%>
          </ul>
        </div>
      </div>
      <!--End row-->
      <!--Row-->

  <div class="row">
    <div class="divider-m tCenter margTSSmall margBSmall clearfix">
      <div class="col-md-12">
        <div class="zigzag medium clearfix "  data-svg-drawing="yes" >
          <svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="45" height="5" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
          <path d="M1.357,12.26 10.807,2.81 20.328,12.332
          29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
          </svg>
        </div>
      </div>
    </div>
  </div>
          <!--End row-->
          <!--Row-->
  <div class="row">
    <ul class="work">
      <%@story.each do |story|%>
      <li class="col-md-4 ">
        <!--Item-->
        <div class="item <%=story.categorystory.cname%>">
          <a  href="project_single.html">
            <div class="desc">
              <h3 class="proj-desc"><%=story.title%>
                <span class="zigzag work clearfix "  data-svg-drawing="yes" >
                  <svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="25" height="10" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
                  <path d="M1.357,12.26 10.807,2.81 20.328,12.332
                  29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
                  </svg>
                </span>
                <span><%=story.categorystory.categoryname%></span>
              </h3>
                </div>

                <img alt="" src="<%=story.image%>">
              </a>

            </div>
            <!--End item-->

            </li>
            <%end%>


            </ul>

            </div>
            <!--End row-->






                        </div>
          <!--End works-->

          <div class="clearfix"></div>

          </div>
          <!--End block content-->



          </div>
          <!--End content-->

app/views/add/_right-content.html.erb
<!--Right content-->
<div class="col-md-9 right-content">
      <!--About Tab-->
    <section id="about" class="bgWhite ofsInBottom hide">
      <!--About -->
    <%=render "add/whoami"%>
    <!--Main title-->
    <%=render "add/skill"%>
    <!--Main title-->
    <%=render "add/experience"%>
    <!--Main title-->
    <%=render "add/education"%>
    <!--Main title-->
    <%=render "add/latestpost"%>
    <!--Button-->
    <%=render "add/footer"%>
    <!--End button-->
</div>
      <!--End about-->
    </section>
<!--End about tab-->
<!--Portfolio Tab-->
<section id="portfolio" class="bgWhite ofsInBottom hide">
<!--Portfolio -->
<div class="portfolio">
<!--Main title-->
  <%=render "add/mywork"%>
  <%=render "add/footer"%>
              <!--End button-->
</div>
              <!--End portfolio-->
</section>
              <!--End portfolio tab-->

<!--Blog Tab-->
<section id="blog" class="bgWhite ofsInBottom hide">
<!--Blog -->
<div class="blog">
                <!--Main title-->
<%=render "add/blog"%>
<%=render "add/footer"%>
</div>
<!--End blog-->
</section>
<!--End blog tab-->
<!--Contact Tab-->
<section id="contact" class="bgWhite ofsInBottom">
<!--Contact -->
<%=render "add/contact"%>
<!--End contact-->
</section>
<!--End contact tab-->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sousavoeurn.com</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application','data-turbolinks-track': 'reload' %>
  </head>

  <body style="background:#efefef" onload="document.refresh();">
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="button margTop ofsInTop tCenter">

    <div class="divider">
        <div class="zigzag large clearfix "  data-svg-drawing="yes" >
<svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
<path d="M1.357,12.26 10.807,2.81 20.328,12.332
29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
</svg>
</div>
</div>


                  <!--Row-->
  <div class="row ">


    <div class="col-md-12">
      <!-- <a class="but opc-1 ico" href="#">Download my cv</a> -->
      <%=link_to "Contact Me",new_contactme_path,:class=>"but opc-1"%>
    
    </div>



    </div>
    <!--End row-->


                </div>